### ISSUE TITLE
Minor backend install sequence error: npm install

### ISSUE THREAD

**Issue by nerdguru** [serverless/scope#4]
Minor thing, but the backend instructions don't explicitly tell you to run `npm install` but instead jump straight to the config file editing.  If you don't run `npm install`, the setup script fails:

> $ sls invoke -f setup
> {
>     "errorMessage": "Cannot find module 'sync-request'",
>     "errorType": "Error",
>     "stackTrace": [
>         "Module.require (module.js:353:17)",
>         "require (internal/module.js:12:17)",
>         "Object.<anonymous> (/var/task/lib/setup.js:4:21)",
>         "Module._compile (module.js:409:26)",
>         "Object.Module._extensions..js (module.js:416:10)",
>         "Module.load (module.js:343:32)",
>         "Function.Module._load (module.js:300:12)",
>         "Module.require (module.js:353:17)"
>     ]
> }

But that's fixed if you run `npm install`, redeploy, and try the setup again.

**Comment by DavidWells** [comment]
Good call! Fixed
