### ISSUE TITLE
Replace dynamodb with S3

### ISSUE THREAD

**Issue by andymac4182** [serverless/scope#7]
Would it be an option to replace dynamodb with s3?  

You can use the list command in s3 to get something similar to scan. This would mean you could open the bucket to be read directly from the client reducing the need for lambda and costs. 

You can use a bucket policy similar to this 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::Example/*"
        },
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::Example"
        }
    ]
}
```

Did an initial bit of work to show how this might be done https://github.com/serverless/scope/compare/master...andymac4182:master

**Comment by Xiphe** [comment]
what would be the benefit of s3 over dynamodb in this scenario?

**Comment by DavidWells** [comment]
If you can prove a direct call to s3 is faster than a dynamoDB call, we would consider this as an option =)

**Comment by QuantumInformation** [comment]
Just don't tell AWS ;) J
